### ISSUE TITLE
Could you share the source code for the Pico firmware?

### ISSUE THREAD

**Issue by ha5dzs** [FreddyVRetro/ISA-PicoMEM#1]
I don't know if you want to keep it propretary, but if possible, I would like to use some of your code that runs on the Pico to implement other functionalities as well.

**Comment by FreddyVRetro** [comment]
Hi,
Source will be released, please be patient.

**Comment by eparadis** [comment]
I haven’t reviewed all the libraries you’re using, but because you are already distributing the binaries and are using code that is GPL’d, you should already be releasing the source code.

I know you want to “get it ready”, but that’s not how it works. Besides, it’s easy. Just put a zip file or tgz file of your source directory into this repo. You will save yourself a lot of trouble if you do it sooner rather than later.

**Comment by FreddyVRetro** [comment]
Hi,

I think the only GPL source used is the Disk BIOS code from DOSBOX, and I had to modify it heavily to adapt to the PicoMEM.

I am sorry but I am not a copywrite expert and it is the first project I did with GitHub.
I will publish the source really soon, I still need to check how to do in a "Clean" way.

Also, why not telling me you like my job or some kind world, because here, you just write me I will have trouble....

**Comment by megatog615** [comment]
It's okay, no need for hostilities. It's fine if you don't know. If you're going to release the whole project source code and you want to pick a license, I suggest GPL2 to be most compatible with the DOSBOX code. If you are worried about how to attribute the DOSBOX project I think all you have to do is just mention that you use code from DOSBOX under the GPL2 license, and see if you can find who wrote the original code and attribute them. Their name might even be in the source files.

**Comment by ha5dzs** [comment]
My experience with sharing the source code has been nothing but positive. You never know when a remote nerd helps you out with a bug or oversight with your code. And a nice, well-documented pull request can make your day!

It really doesn't matter if the code is 'clean' or not. Nobody will judge you how you write your code, because what you are doing here is incredibly specific. Besides, version tracking can help a lot if you accidentally break something while developing. I found that it is much better to leave breadcrumbs that help others (and your future self) understand why things are the way things are. So people can refer to some breaking change that happened in commit XYZ and discuss it.

I asked about the code so that I could add some machine-level interfaces to the Pico hardware, so one could literally handle them from the OS environment. I principally wanted the I2C interface so I can connect it to other gadgets, but there are lots of possibilities. Not for the least, I wanted to try writing some DOS drivers.

Without seeing any of that code, I cannot even tell if there are any design bottlenecks in place that would prevent my idea from being implemented. Say, because you used some weird time-critical bitbanging to counter-act some gate-level decision treshold problem due to some noise on the bus (I actually had this one happen to me before), and me firing an interrupt would upset that timing.

**Comment by megatog615** [comment]
I think this issue should be kept open until the promise of the source code release is met.

**Comment by FreddyVRetro** [comment]
Hi,

 

Maybe it was not seen that most of the source code and all the GNU parts are published.

 

Regards,

FreddyV

 

De : mega ***@***.***> 
Envoyé : jeudi 19 septembre 2024 23:09
À : FreddyVRetro/ISA-PicoMEM ***@***.***>
Cc : FreddyV ***@***.***>; State change ***@***.***>
Objet : Re: [FreddyVRetro/ISA-PicoMEM] Could you share the source code for the Pico firmware? (Issue #1)

 

I think this issue should be kept open until the promise of the source code release is met.

**Comment by megatog615** [comment]
Will the firmware source be released?

**Comment by FreddyVRetro** [comment]
Hi,

I confirm I finished the code cleanup and reorganisation I wanted before release, to be published for the next firmware release.
(Less than one week I hope)

**Comment by FreddyVRetro** [comment]
> Will the firmware source be released?

Most of the source is already release, did you see it ?

**Comment by FreddyVRetro** [comment]
Hi,

Source is now published :)

**Comment by FreddyVRetro** [comment]
Hi,
You asked for the source, now that it is released, do you plan to do something with it ?

**Comment by megatog615** [comment]
The various readmes have conflicting information, such as the readme file in the src/ directory saying that the source isn't 100% released, and the top readme file saying that the project is currently closed.

I also can't find a license file. If there was a source license I think people would be more comfortable working with the code.

**Comment by FreddyVRetro** [comment]
So I have my answer, you don't care about the code.

**Comment by megatog615** [comment]
...huh?

**Comment by FreddyVRetro** [comment]
I react like this because if I have to put more effort to check all the legal things than doing the code, it is not worth it....
I will check that, thanks

**Comment by FreddyVRetro** [comment]
Hi @ha5dzs,
I ansered to megatog who maybe did not see my question.

**Comment by megatog615** [comment]
> Hi @megatog615, I react like this because if I have to put more effort to check all the legal things than doing the code, it is not worth it.... I will check that, thanks

Hi. I tried to send you a message on discord to try to hash this out with you. First, it is of great interest to me that the source code is released because as ha5dzs said, others are very interested in the code and so am I by extension. I am excited to see what kinds of new things these interested people are going to add and fix, so that is ky motivation. I like engaging in open source projects.

Second, it is very easy to add a license. If all the code is yours, then you can just pick a license like GPLv2 and put it in a text file called LICENSE in the root of the source code directory tree. If it's a bit more complicated, you can just mention the relevant information in the readme.

Nobody is trying to hassle you; this is just the tiny bit of work that needs to be done and everyone will be satisfied.
